### ISSUE TITLE
a issue in the code "nav_node.py".

### ISSUE THREAD

**Issue by shenyehui** [MIT-SPARK/Loc-NeRF#7]
Thanks for your great work！
I meet this issue:
Traceback (most recent call last):
  File "/home/shen/catkin_ws/devel/lib/locnerf/nav_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/shen/catkin_ws/src/Loc-NeRF/src/nav_node.py", line 489, in <module>
    mcl_local = Navigator(img_num, dataset_name)
  File "/home/shen/catkin_ws/src/Loc-NeRF/src/nav_node.py", line 37, in __init__
    self.get_initial_distribution()
  File "/home/shen/catkin_ws/src/Loc-NeRF/src/nav_node.py", line 91, in get_initial_distribution
    euler = (gtsam.Rot3.AxisAngle(axis, angle)).ypr()
AttributeError: type object 'gtsam.gtsam.Rot3' has no attribute 'AxisAngle'
[nav_node-1] process has died [pid 11955, exit code 1, cmd /home/shen/catkin_ws/devel/lib/locnerf/nav_node.py __name:=nav_node __log:=/home/shen/.ros/log/cac10c9e-7e46-11ee-a570-c5354750a6c4/nav_node-1.log].
log file: /home/shen/.ros/log/cac10c9e-7e46-11ee-a570-c5354750a6c4/nav_node-1*.log

can you give a advice to solve it?

**Comment by shenyehui** [comment]
what is version of gtsam？
